### ISSUE TITLE
How to use the requested privileges?

### ISSUE THREAD

**Issue by Jacalz** [amenzhinsky/go-polkit#2]
Fist of all, thanks for creating this library. Seems to be a very clean implementation.

I am creating a graphical application for flashing iso images to usb disks. To do this, I need to request `org.freedesktop.udisks2.open-device`, as far as I can see from what gnome multi writer is doing. I've gotten that far using this library by following the example to request password. Wonderful progress and I'm very happy to have learned a lot about polkit in the progress.

However, when I try to open the disk for reading using the `os.OpenFile()` function, I get an error about it not having that permission (I have verified that the code works when running the app without polkit and with sudo instead). Is there any way I can make use of the elevated privileges that I have requested?

**Comment by amenzhinsky** [comment]
Hi, I haven't used polkit for a while, but as far I can remember you need create a rules file that defines access to disks on your system

**Comment by Jacalz** [comment]
Thanks for the reply. I went digging into gnome multiwriter again and found this: https://github.com/GNOME/gnome-multi-writer/blob/693ac66bde962802985015256c15ccdc0439250a/data/org.gnome.MultiWriter.policy.in. You mean that I need to do something like that to get it working? I'm not sure how their probe works but I will try and see what I can get working.

**Comment by Jacalz** [comment]
I can't quite get it to work. This is the code that I have for using your library:
```go
package flash

import (
	"errors"
	"io"
	"os"

	"fyne.io/fyne/v2"
	"github.com/amenzhinsky/go-polkit"
)

var unathurizedError = errors.New("the user is unathurized or the request was dismissed")

func StartFlash(image, disk string) error {
	// TODO: Support reading compressed images.
	src, err := os.Open(image)
	if err != nil {
		fyne.LogError("Could not load image:", err)
		return err
	}
	defer src.Close()

	auth, err := polkit.NewAuthority()
	if err != nil {
		fyne.LogError("Could not create polkit authority:", err)
		return err
	}

	msg, err := auth.CheckAuthorization("org.freedesktop.udisks2.open-device", nil, polkit.CheckAuthorizationAllowUserInteraction, "")
	if err != nil {
		fyne.LogError("Could not aquire permission:", err)
		return err
	} else if !msg.IsAuthorized {
		fyne.LogError("Could not get authorization:", unathurizedError)
		return unathurizedError
	}

	dst, err := os.OpenFile(disk, os.O_RDWR, 0755)
	if err != nil {
		fyne.LogError("Could not open target disk:", err)
		return err
	}
	defer dst.Close()

	_, err = io.Copy(dst, src)
	if err != nil {
		fyne.LogError("Could not copy contents to disk:", err)
		return err
	}

	return nil
}
```

And this is my polkit action file:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE policyconfig PUBLIC
 "-//freedesktop//DTD PolicyKit Policy Configuration 1.0//EN"
 "http://www.freedesktop.org/standards/PolicyKit/1.0/policyconfig.dtd">
<policyconfig>
  <vendor>Jacalz</vendor>
  <vendor_url>https://github.com/Jacalz</vendor_url>

  <action id="io.github.jacalz.detch.access">
    <description>Access a disk</description>
    <message>Authentication is required to access the device</message>
    <icon_name>drive-harddisk-usb</icon_name>
    <defaults>
      <allow_any>auth_admin</allow_any>
      <allow_inactive>auth_admin</allow_inactive>
      <allow_active>auth_admin_keep</allow_active>
    </defaults>
    <annotate key="org.freedesktop.policykit.exec.path">/usr/bin/detch</annotate>
    <annotate key="org.freedesktop.policykit.exec.allow_gui">true</annotate>
  </action>

</policyconfig>
```

The popup comes up and I can type my password. The autorization comepletes bu there doesn't ever seem to be any privileges that are elevated. I always get an error about not having permissions for accessing the device when I try to read the drive with the `OpenFile` function.

**Comment by amenzhinsky** [comment]
I'm sorry that I confused you with defining your own policy, you don't really need to use polkit here at all, it's used mostly by daemonish apps that provide DBus API and UDisks2 already provide everything you need:

http://storaged.org/doc/udisks2-api/latest/gdbus-org.freedesktop.UDisks2.Block.html#gdbus-method-org-freedesktop-UDisks2-Block.OpenDevice

```go
func run() error {
	conn, err := dbus.SystemBus()
	if err != nil {
		return err
	}

	o := conn.Object("org.freedesktop.UDisks2", "/org/freedesktop/UDisks2/block_devices/nvme0n1")
	var fd dbus.UnixFD
	if err := o.Call("org.freedesktop.UDisks2.Block.OpenDevice", 0,
		"r", map[string]interface{}{},
	).Store(&fd); err != nil {
		return err
	}

	f := os.NewFile(uintptr(fd), "[disk-name]")
	fmt.Println(f.Fd())
	return nil
}
```

Only replace `nvme0n1` with the required disk name.

**Comment by Jacalz** [comment]
Massive thanks. I will make sure that you are mentioned and thanked in the project readme once I open it up.
That is working much better. I now have this code:
```go
func StartFlash(image, disk string) error {
	// TODO: Support reading compressed images.
	src, err := os.Open(image)
	if err != nil {
		fyne.LogError("Could not load image:", err)
		return err
	}
	defer src.Close()

	conn, err := dbus.SystemBus()
	if err != nil {
		return err
	}

	// disk in this case is "sdf"

	o := conn.Object("org.freedesktop.UDisks2", dbus.ObjectPath("/org/freedesktop/UDisks2/block_devices/"+disk))
	var fd dbus.UnixFD
	if err := o.Call("org.freedesktop.UDisks2.Block.OpenDevice", 0, "r", map[string]interface{}{}).Store(&fd); err != nil {
		return err
	}

	// Also tried with only passing disk here, but it makes no difference.

	dst := os.NewFile(uintptr(fd), "/dev"+disk)
	defer dst.Close()

	_, err = io.Copy(dst, src)
	if err != nil {
		fyne.LogError("Could not copy contents to disk:", err)
		return err
	}

	return nil
}
```

However, I get this error:
```
2021/11/26 11:37:08 Fyne error:  Could not copy contents to disk:
2021/11/26 11:37:08   Cause: write /dev/sdf: bad file descriptor
2021/11/26 11:37:08   At: /home/jacob/Git/detch/internal/flash/flash.go:36
```

Any idea?

**Comment by amenzhinsky** [comment]
"r" opens disk only for reading

**Comment by Jacalz** [comment]
Ah, I see. I think that managed to fix it. Thanks a lot :)
